### ISSUE TITLE
Use boolean values for debug-mode(etc) not string

### ISSUE THREAD

**Issue by ewohnlich** [plone/cookiecutter-zope-instance#10]
`debug-mode {{ "on" if cookiecutter.debug_mode == "True" else "off" }}`
Setting it to `debug_mode: true` in your yaml does not work, you have to use `debug_mode: "True"`. I am guessing this is because cookiecutter did not support boolean values when this template was created. Changing this to require a boolean may have unexpected implications for legacy templates - an alternative would be to change the default value in cookiecutter.json to "True" to hint that it's looking for a string.

**Comment by jensens** [comment]
Yes, this needs improvement.

**Comment by jensens** [comment]
this will be fixed with v2.0, https://github.com/plone/cookiecutter-zope-instance/commit/fcfdc79e72f74028b71f8735f18ac078f6021e38
