### ISSUE TITLE
Adding extra environment variables has no effect

### ISSUE THREAD

**Issue by oggers** [plone/cookiecutter-zope-instance#17]
I'm trying to add extra environment variables in instance.yaml, but they are not rendered in instance/etc/zope.conf. Only changes in the values of the 2 default variables (zope_i18n_compile_mo_files, CHAMELEON_CACHE) are rendered.

How am I supposed to include new environment variables?

**Comment by jensens** [comment]
see #15

**Comment by oggers** [comment]
Oh I see, it's a bug in cookiecutter itself.

I didn't relate the other issue at first sight.

**Comment by jensens** [comment]
I fixed it in cookiecutter (and a few seconds ago I fixed a test coverage glitch there), waiting now for review/merge and release.
