### ISSUE TITLE
How can i setup cookiecutter for developing a custom plone addon

### ISSUE THREAD

**Issue by 1letter** [plone/cookiecutter-zope-instance#2]
@jensens 
How can i include a custom addon which is create with plonecli?
My directory layout:

```
- dev.test1 --> the addon created by plonecli
- instance
  - etc
  - var
  - inituser
- venv
- config.yaml --> the cookiecutter config
```
is this possible via the config.yaml or should i use the normal buildout inside the custom addon? General asked, is cookiecutter ready to use for development process of Plone Addons?
For me it's unclear, what is the standard  way? plonecli with the buildout or cookiecutter... i'm a little bit confused.

**Comment by jensens** [comment]
The cookiecutter here does one thing: create configuration  to run a zope instance. Nothing else.

Eventually youre looking for tools like mxdev and plonecli
